const Actions = {
  QUESTION_LIST_SET: "QUESTION_LIST_SET",
  CURRENT_EXAM_CHANGED: "CURRENT_EXAM_CHANGED",
  QUESTION_ANSWERED: "QUESTION_ANSWERED",
  LOADING_STARTED: "LOADING_STARTED",
  LOADING_DONE: "LOADING_DONE",
  SCREEN_FORWARD: "SCREEN_FORWARD",
  SCREEN_PREVIOUS: "SCREEN_PREVIOUS",
  LOADING_MESSAGE_CHANGED: "LOADING_MESSAGE_CHANGED",
};

export default Actions;
